vaadin:
  whitelisted-packages:
    - com.vaadin
    - org.vaadin
    - dev.hilla
    - com.flowingcode
  frontend:
    hotdeploy: false

spring:
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true